# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ember For All
email: briggszj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learning EmberJS shouldn't be hard. This site proves that it isn't.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://emberforall.com" # the base hostname & protocol for your site
twitter_username: theotherzach
github_username:  theotherzach

# Build settings
markdown: kramdown

kramdown:
  input: GFM
